arm:
  type: ur10
sensors:
  # over agv1
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [0.3, 3.15, 1.5]
      rpy: [0, 'pi/2', 0]
  # over agv2
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [0.3, -3.12, 1.5]
      rpy: [0, 'pi/2', 0]
  # over bins
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [-0.742101, 0.970000, 0.979857]
      rpy: [0, 0.727159, 0]
  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [-0.748136, 0.200000, 0.982218]
      rpy: [0, 0.725374, 0]
  logical_camera_5:
    type: logical_camera
    pose:
      xyz: [-0.748136, -0.500000, 0.982218]
      rpy: [0, 0.725374, 0]
  logical_camera_6:
    type: logical_camera
    pose:
      xyz: [-0.720640, -1.415484, 0.947125]
      rpy: [0, 0.717756, 0]
